cmake_minimum_required(VERSION 3.16)
project(qr_planning)
find_package(ament_cmake REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(yaml-cpp REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_action REQUIRED)
find_package(qr_interfaces REQUIRED)
add_executable(finite_sequence src/finite_sequence.cpp)
target_compile_features(finite_sequence PRIVATE cxx_std_17)
target_include_directories(finite_sequence PRIVATE include)
ament_target_dependencies(finite_sequence rclcpp rclcpp_action qr_interfaces)
target_link_libraries(finite_sequence yaml-cpp)
install(TARGETS finite_sequence DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY config DESTINATION share/${PROJECT_NAME})
install(DIRECTORY include/ DESTINATION include)
ament_export_include_directories(include)
ament_export_dependencies(Eigen3 yaml-cpp)
if(BUILD_TESTING)
 find_package(ament_cmake_gtest REQUIRED)
 ament_add_gtest(test_finite_template test/test_finite_template.cpp)
 target_include_directories(test_finite_template PRIVATE include)
 target_link_libraries(test_finite_template yaml-cpp)
 ament_add_gtest(test_geometry test/test_geometry.cpp)
 target_include_directories(test_geometry PRIVATE include)
 target_link_libraries(test_geometry Eigen3::Eigen)
endif()
ament_package()
