<?xml version="1.0"?>
<package format="3">
  <name>qr_bringup</name>
  <version>0.1.0</version>
  <description>QR quadruped bringup</description>
  <maintainer email="maintainer@example.com">Custom Dog Team</maintainer>
  <license>BSD-3-Clause</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>custom_dog_control</exec_depend>
  <exec_depend>qr_course</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
  <exec_depend>launch</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>controller_manager_msgs</exec_depend>
</package>
